### ISSUE TITLE
Emojis in GT Tables loses colors

### ISSUE THREAD

**Issue by billyfryer** [EmilHvitfeldt/emoji#4]
Whenever I try to save a {gt} table using the `gtsave()` function that contains an emoji, the saved emoji loses its color.

**Comment by EmilHvitfeldt** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)", and follow the advice further down that page.

**Comment by billyfryer** [comment]
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(emoji)
library(gt)

sample_data <- data.frame(Athlete = c("Alice", "Billy", "Charley"),
           Medal = c("Silver", "Gold", "Bronze"))

data_w_emojis <- sample_data %>% 
  mutate(Medal = emoji::medal(Medal))

data_w_emojis %>% gt() %>% gtsave("No Colored Emojis.png")
```

![](https://i.imgur.com/xrsZLOU.png)

<sup>Created on 2022-02-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


Thanks for answering so fast!

**Comment by EmilHvitfeldt** [comment]
A quick look on my end, doesn't allow me to replicate the result.

![No Colored Emojis](https://user-images.githubusercontent.com/14034784/153530384-f3eeab9f-beef-4e8f-8cf5-98f340143130.png)

I'm going to refer you to open an issue in the {gt} repository as it is more like where the problems are occurring https://github.com/rstudio/gt/issues.
